/**
 * @module markdown.test
 *
 * Regression tests for the mail-body markdown renderer's auto-linker.
 *
 * The bare-URL auto-link pass guards only against URLs sitting inside an
 * href/src attribute (`[^"=]` before the match). A URL used as a link's
 * *display text* — the common autogenerated-mail pattern
 * `[https://foo](https://foo)` — is preceded by `>` after the explicit-link
 * pass, so the auto-linker wrapped it in a second `<a>` nested inside the
 * first: invalid HTML that browsers split into broken sibling anchors. The
 * fix masks finished anchors during the auto-link pass; a plain `>` guard
 * would have stopped URLs inside <strong>/<em>/<code> from linking at all.
 */

import { describe, test, expect } from 'vitest';
import { renderMarkdown } from './markdown.js';

const anchorCount = (html: string): number => (html.match(/<a /g) ?? []).length;

describe('auto-linking bare URLs', () => {
  test('links a bare URL in plain text', () => {
    const html = renderMarkdown('see https://example.com/x for details');
    expect(html).toContain('<a href="https://example.com/x" target="_blank" rel="noopener">https://example.com/x</a>');
  });

  test('does not nest an anchor inside a link whose text is itself a URL', () => {
    const html = renderMarkdown('[https://example.com/x](https://example.com/x)');

    expect(anchorCount(html)).toBe(1);
    expect(html).toContain('<a href="https://example.com/x" target="_blank" rel="noopener">https://example.com/x</a>');
    // No leftover masking sentinel either.
    expect(html).not.toContain('\u0000');
  });

  test('still auto-links a URL wrapped in emphasis', () => {
    const html = renderMarkdown('**https://example.com/x**');
    expect(html).toContain('<strong><a href="https://example.com/x"');
  });

  test('leaves an ordinary link with word text alone', () => {
    const html = renderMarkdown('[docs](https://example.com/docs) and https://example.com/more');
    expect(anchorCount(html)).toBe(2);
    expect(html).toContain('>docs</a>');
  });

  test('does not misread digits between links as a masking sentinel', () => {
    const html = renderMarkdown('[a](https://a.example) 0 [b](https://b.example)');
    expect(anchorCount(html)).toBe(2);
    expect(html).toContain('https://a.example');
    expect(html).toContain('https://b.example');
    expect(html).toContain(' 0 ');
  });
});
