/**
 * @module dm-87.test
 *
 * Card test: Seek without Success (dm-87)
 * Type: hazard-event (short)
 *
 * "Discard a ranger agent at target company's new site. Company must
 * immediately return to its site of origin. Cannot be played if your
 * opponent is a minion player."
 *
 * Card shape:
 *   - effects[0]: discard-agent-at-site (skill: "ranger")
 *   - effects[1]: company-return-to-origin
 *
 * Engine support:
 *   - discard-agent-at-site: legal actions generated by
 *     `discardAgentAtSiteActions()` (legal-actions/movement-hazard.ts) —
 *     enforces the ranger-skill requirement, the site-location check, the
 *     `inPlayAtTurnStart`/not-wounded conditions (CoE rule 2.IV.4), and the
 *     minion-player restriction. The card is a plain short-event (no
 *     combat), so it resolves through the ordinary chain
 *     (`initiateOrPushChain`): `applyDiscardAgentAtSite()` (chain-reducer.ts)
 *     discards the chosen agent, then the paired `company-return-to-origin`
 *     effect (`applyCompanyReturnToOrigin`) forces the company back to its
 *     site of origin.
 *
 * Dâsakûn (dm-4) is used as the ranger-skill agent throughout: a plain
 * "warrior, ranger" minion agent with no effects of its own, so the tests
 * exercise dm-87's own mechanism rather than any self-ability of the agent.
 */

import { describe, test, expect, beforeEach } from 'vitest';
import {
  PLAYER_1, PLAYER_2,
  ARAGORN,
  RIVENDELL, BREE,
  buildTestState, resetMint, makeMHState,
  dispatch, resolveChain, viableActions,
  RESOURCE_PLAYER, HAZARD_PLAYER,
  Alignment,
  CardStatus,
  makeAgent, makeBillFernyAgent,
} from '../test-helpers.js';
import { Phase } from '../../index.js';
import type {
  AgentInPlay, CardDefinitionId, CardInstanceId, GameState,
  MovementHazardPhaseState, PlayHazardAction, SiteInPlay,
} from '../../index.js';

const SEEK_WITHOUT_SUCCESS = 'dm-87' as CardDefinitionId;
const DASAKUN = 'dm-4' as CardDefinitionId;

const BREE_SITE_ID = 'test-dm87-bree-site' as CardInstanceId;
const BREE_SITE: SiteInPlay = {
  instanceId: BREE_SITE_ID,
  definitionId: BREE,
  status: CardStatus.Untapped,
};

function rangerAgent(opts?: {
  revealed?: boolean;
  status?: CardStatus;
  inPlayAtTurnStart?: boolean;
  siteStack?: readonly SiteInPlay[];
}): AgentInPlay {
  const base = makeAgent(DASAKUN, { revealed: opts?.revealed ?? true });
  return {
    ...base,
    siteStack: opts?.siteStack ?? [BREE_SITE],
    character: { ...base.character, status: opts?.status ?? CardStatus.Untapped },
    inPlayAtTurnStart: opts?.inPlayAtTurnStart ?? true,
  };
}

describe('Seek without Success (dm-87)', () => {
  beforeEach(() => resetMint());

  function baseState(agents: AgentInPlay[] = [rangerAgent()]): GameState {
    const state = buildTestState({
      phase: Phase.MovementHazard,
      activePlayer: PLAYER_1,
      players: [
        {
          id: PLAYER_1,
          companies: [{ site: RIVENDELL, characters: [ARAGORN], destinationSite: BREE }],
          hand: [],
          siteDeck: [BREE],
        },
        {
          id: PLAYER_2,
          companies: [{ site: RIVENDELL, characters: [] }],
          hand: [SEEK_WITHOUT_SUCCESS],
          siteDeck: [],
        },
      ],
    });
    return {
      ...state,
      phaseState: makeMHState(),
      players: [
        state.players[RESOURCE_PLAYER],
        { ...state.players[HAZARD_PLAYER], agents },
      ] as typeof state.players,
    };
  }

  test('playable when a ranger agent is at the company\'s new site', () => {
    const state = baseState();
    const plays = viableActions(state, PLAYER_2, 'play-hazard');
    expect(plays).toHaveLength(1);
    const action = plays[0].action as PlayHazardAction;
    expect(action.agentInstanceId).toBeDefined();
  });

  test('NOT playable when the only agent present does not have the ranger skill', () => {
    const state = baseState([makeBillFernyAgent()]); // warrior/scout, home site Bree — but not a ranger
    const plays = viableActions(state, PLAYER_2, 'play-hazard');
    expect(plays.filter(a => a.viable)).toHaveLength(0);
  });

  test('NOT playable when there are no agents at all', () => {
    const state = baseState([]);
    const plays = viableActions(state, PLAYER_2, 'play-hazard');
    expect(plays.filter(a => a.viable)).toHaveLength(0);
  });

  test('NOT playable against a minion (Ringwraith) opponent', () => {
    const state = baseState();
    const asMinion: GameState = {
      ...state,
      players: [
        { ...state.players[RESOURCE_PLAYER], alignment: Alignment.Ringwraith },
        state.players[HAZARD_PLAYER],
      ] as typeof state.players,
    };
    const plays = viableActions(asMinion, PLAYER_2, 'play-hazard');
    expect(plays.filter(a => a.viable)).toHaveLength(0);
  });

  test('NOT playable when the company is not moving — it has no new site', () => {
    const state = buildTestState({
      phase: Phase.MovementHazard,
      activePlayer: PLAYER_1,
      players: [
        { id: PLAYER_1, companies: [{ site: RIVENDELL, characters: [ARAGORN] }], hand: [], siteDeck: [] },
        { id: PLAYER_2, companies: [{ site: RIVENDELL, characters: [] }], hand: [SEEK_WITHOUT_SUCCESS], siteDeck: [] },
      ],
    });
    const stationary: GameState = {
      ...state,
      phaseState: makeMHState(),
      players: [
        state.players[RESOURCE_PLAYER],
        { ...state.players[HAZARD_PLAYER], agents: [rangerAgent()] },
      ] as typeof state.players,
    };
    const plays = viableActions(stationary, PLAYER_2, 'play-hazard');
    expect(plays.filter(a => a.viable)).toHaveLength(0);
  });

  test('NOT playable when the ranger agent is at a different site than the company\'s new site', () => {
    const elsewhere: SiteInPlay = {
      instanceId: 'test-dm87-rivendell-site' as CardInstanceId,
      definitionId: RIVENDELL,
      status: CardStatus.Untapped,
    };
    const state = baseState([rangerAgent({ siteStack: [elsewhere] })]);
    const plays = viableActions(state, PLAYER_2, 'play-hazard');
    expect(plays.filter(a => a.viable)).toHaveLength(0);
  });

  test('NOT playable when the ranger agent is wounded', () => {
    const state = baseState([rangerAgent({ status: CardStatus.Inverted })]);
    const plays = viableActions(state, PLAYER_2, 'play-hazard');
    expect(plays.filter(a => a.viable)).toHaveLength(0);
  });

  test('a tapped ranger agent may still be discarded — no tap is required', () => {
    const state = baseState([rangerAgent({ status: CardStatus.Tapped })]);
    const plays = viableActions(state, PLAYER_2, 'play-hazard');
    expect(plays.filter(a => a.viable)).toHaveLength(1);
  });

  test('a face-down ranger agent at the destination may be discarded too', () => {
    const state = baseState([rangerAgent({ revealed: false })]);
    const plays = viableActions(state, PLAYER_2, 'play-hazard');
    expect(plays.filter(a => a.viable)).toHaveLength(1);
  });

  test('NOT playable when the ranger agent was not in play at turn start', () => {
    const state = baseState([rangerAgent({ inPlayAtTurnStart: false })]);
    const plays = viableActions(state, PLAYER_2, 'play-hazard');
    expect(plays.filter(a => a.viable)).toHaveLength(0);
  });

  test('playing the card discards the chosen agent and marks the company for return to its site of origin', () => {
    const state = baseState();
    const companyId = state.players[RESOURCE_PLAYER].companies[0].id;
    const plays = viableActions(state, PLAYER_2, 'play-hazard');
    expect(plays).toHaveLength(1);

    const afterPlay = dispatch(state, plays[0].action);
    const after = resolveChain(afterPlay);
    expect(after.chain).toBeNull();

    // The agent is discarded: gone from agents, its character card in the
    // hazard player's discard pile, its site-stack site back in the hazard
    // player's site deck.
    expect(after.players[HAZARD_PLAYER].agents).toHaveLength(0);
    expect(after.players[HAZARD_PLAYER].discardPile.some(c => c.definitionId === DASAKUN)).toBe(true);
    expect(after.players[HAZARD_PLAYER].siteDeck.some(c => c.instanceId === BREE_SITE_ID)).toBe(true);

    // Rule 2.IV.4: the company is marked to return to its site of origin
    // (finalized by `endCompanyMH` once the M/H phase for this company
    // completes) and a site-phase-do-nothing constraint blocks its upcoming
    // site phase, sourced from the played Seek without Success card.
    expect((after.phaseState as MovementHazardPhaseState).returnedToOrigin).toBe(true);
    expect(after.activeConstraints.some(
      c => c.kind.type === 'site-phase-do-nothing'
        && c.target.kind === 'company' && c.target.companyId === companyId
        && c.sourceDefinitionId === SEEK_WITHOUT_SUCCESS,
    )).toBe(true);
  });

  test('Seek without Success is discarded from hand and counts against the hazard limit', () => {
    const state = baseState();
    const countBefore = (state.phaseState as MovementHazardPhaseState).hazardsPlayedThisCompany;
    const plays = viableActions(state, PLAYER_2, 'play-hazard');

    const afterPlay = dispatch(state, plays[0].action);
    const after = resolveChain(afterPlay);

    expect(after.players[HAZARD_PLAYER].hand).toHaveLength(0);
    expect(after.players[HAZARD_PLAYER].discardPile.some(c => c.definitionId === SEEK_WITHOUT_SUCCESS)).toBe(true);
    const countAfter = (after.phaseState as MovementHazardPhaseState).hazardsPlayedThisCompany;
    expect(countAfter).toBe(countBefore + 1);
  });
});
