/**
 * @module features/action-types
 *
 * The canonical, ordered list of every `GameAction.type` discriminant. The
 * action featurizer maps a candidate's type string to `index + 1` in this
 * list (0 is reserved for unknown types, so a future engine action degrades
 * gracefully instead of crashing training).
 *
 * **Indices are permanent. A new type goes at the END of this list, never
 * in alphabetical position.** The order below is historical rather than
 * sorted: it is a serialization format shared with every trained
 * checkpoint, so inserting a type mid-list shifts every index after it and
 * silently re-labels that many action types for every existing model.
 * Measured: certifying tw-282 inserted `choose-peek-deck` at index 31,
 * shifting 127 of 158 types, and the champion went from 10-9 against the
 * heuristic to 0-18. A coverage test asserts that actions seen in real
 * games all resolve to a known index.
 */

/** Every `GameAction.type` string, sorted, extracted from `@meccg/shared` `types/actions-*.ts`. */
export const ACTION_TYPES: readonly string[] = [
  'activate-granted-action',
  'activate-org-fetch',
  'add-character-to-deck',
  'agent-discard-return-to-origin',
  'agent-heal',
  'agent-influence-attempt',
  'agent-key-creatures',
  'agent-move',
  'agent-move-back',
  'agent-return-home',
  'agent-strike-roll',
  'agent-tap-attack',
  'agent-turn-face-down',
  'agent-untap',
  'allocate-cvcc-excess',
  'apply-attacker-attack-option',
  'arrange-deck-top-card',
  'assign-starting-item',
  'assign-strike',
  'body-check-roll',
  'call-free-council',
  'cancel-attack',
  'cancel-auto-attack',
  'cancel-by-tap',
  'cancel-influence',
  'cancel-movement',
  'cancel-return-to-origin',
  'cancel-strike',
  'cancel-weapon-effects',
  'card-sideboard-to-deck',
  'choose-great-hunt-source',
  'choose-revealed-card',
  'choose-strike-order',
  'convert-creature-to-ally',
  'corruption-check',
  'counter-cancel-attack',
  'counter-cancel-roll',
  'deck-exhaust',
  'declare-agent-attack',
  'declare-company-attack',
  'declare-path',
  'desire-choose-penalty',
  'desire-choose-shown-card',
  'discard-card',
  'discard-card-for-hazard-limit',
  'discard-character',
  'discard-for-evil-hour-movement',
  'discard-item-from-company',
  'discard-stage-resource',
  'discard-to-recruit',
  'draft-pick',
  'draft-stop',
  'draw-cards',
  'enter-site',
  'exchange-sideboard',
  'extra-mh-move',
  'face-strike-on-tap',
  'faction-influence-roll',
  'fetch-from-pile',
  'fetch-from-sideboard',
  'fetch-hazard-from-sideboard',
  'finished',
  'flattery-attempt',
  'flee-from-strike',
  'force-discard-card',
  'gangways-extra-move',
  'gold-ring-test-roll',
  'great-hunt-attack-with-creature',
  'halve-strikes',
  'haven-join-attack',
  'haven-return',
  'influence-attempt',
  'left-behind-rejoin',
  'manifestation-swap',
  'merge-companies',
  'modify-attack',
  'move-to-company',
  'move-to-influence',
  'not-playable',
  'opponent-influence-attempt',
  'opponent-influence-defend',
  'order-effects',
  'order-passives',
  'pair-resource-with-cof',
  'pass',
  'pass-chain-priority',
  'pay-event-maintenance',
  'pay-hazard-limit-to-untap-card',
  'pay-movement-tax',
  'pay-site-tax',
  'place-character',
  'place-on-guard',
  'place-starting-company-event',
  'plan-movement',
  'play-agent-hazard',
  'play-agent-manifestation',
  'play-character',
  'play-creature-from-discard',
  'play-hazard',
  'play-hero-resource',
  'play-long-event',
  'play-minor-item',
  'play-permanent-event',
  'play-reserved-creature',
  'play-ring-after-test',
  'play-short-event',
  'play-site-auto-attack',
  'play-strike-event',
  'play-wizard-from-search',
  'protect-from-assignment',
  'reanimate-from-discard',
  'remove-revealed-card',
  'rescue-prisoner',
  'reserve-creature',
  'reshuffle-card-from-hand',
  'resolve-dice-check',
  'resolve-strike',
  'restore-character-by-effect',
  'return-attached-to-hand',
  'reveal-agent',
  'reveal-on-guard',
  'roll-initiative',
  'run-home',
  'salvage-item',
  'seized-by-terror-roll',
  'select-card-bearer',
  'select-company',
  'select-forewarned-attack',
  'select-stage-resource-site',
  'select-starting-site',
  'shield-discard-roll',
  'shuffle-play-deck',
  'sideboard-with-nazgul',
  'skip-wizard-search',
  'spawn-replay-creature',
  'split-company',
  'start-hazard-sideboard-to-deck',
  'start-hazard-sideboard-to-discard',
  'start-sideboard-to-deck',
  'start-sideboard-to-discard',
  'stay-her-appetite-roll',
  'store-item',
  'support-corruption-check',
  'support-strike',
  'take-trophy',
  'tap-ally-body-check-boost',
  'tap-ally-combat-boost',
  'tap-ally-discard-hazard',
  'tap-alt-permanent-event',
  'tap-character-by-effect',
  'tap-hazard-card-for-limit',
  'tap-item-for-strike',
  'test-ring-at-site',
  'transfer-item',
  'transfer-returned-item',
  'under-deeps-roll',
  'untap',
  'voluntary-discard-in-play',
  // Appended out of alphabetical order deliberately — see the note above.
  // Added by certifying tw-282 (Mirror of Galadriel).
  'choose-peek-deck',
  // Added with the CoE 9.16 item-switching declaration.
  'use-item',
  // Added with the CoE 3.47 end-of-organization-phase influence overflow.
  'influence-overflow-discard',
  // Added by certifying tw-326 (Shadowfax).
  'ally-tap-extra-mh-phase',
  // Added with the sideboard-access cancel action.
  'cancel-sideboard-access',
];

/** Fast index lookup: action type string → 1-based index (0 = unknown). */
const ACTION_TYPE_INDEX: ReadonlyMap<string, number> = new Map(
  ACTION_TYPES.map((type, i) => [type, i + 1]),
);

/** Maps an action type to its stable embedding index; 0 for unknown types. */
export function actionTypeIndex(type: string): number {
  return ACTION_TYPE_INDEX.get(type) ?? 0;
}
